default_language_version:
  python: python3.13

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
        exclude: uv.lock
    -   id: check-toml
    -   id: check-yaml
    -   id: check-added-large-files

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.3
    hooks:
      - id: ruff
        args:
          - --fix
      - id: ruff-format

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: "./scripts/run_mypy"
        language: system
        types: [python]
        require_serial: true
        verbose: true
