services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    # Infinite loop to keep container alive doing nothing
    command:
      - fastapi
      - run
      - --reload
      - "src/main/app.py"
    volumes:
      - ./src/:/app/src/
